# Generated by Django 5.1.5 on 2025-01-23 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('line1', models.CharField(blank=True, max_length=255, null=True)),
                ('line2', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments_app.address')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.CharField(blank=True, max_length=255, null=True)),
                ('livemode', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('us_bank_account', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments_app.billingdetails')),
            ],
        ),
    ]
