# Generated by Django 5.1.5 on 2025-02-06 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_stripe_customer_id_customer_customer_id'),
        ('payments_app', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingdetails',
            name='address',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='billing_details',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_email', models.EmailField(max_length=255)),
                ('total_amount', models.IntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=255)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='BillingDetails',
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
