# Generated by Django 5.1.5 on 2025-02-06 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='stripe_customer_id',
            new_name='customer_id',
        ),
    ]
